"""§2.9 — Estudio de viabilidad económica básica.

Contexto autónomo: el dominio expone parámetros económicos y el cálculo del
estudio (ingresos − costes = margen). Los datos se persisten en
`proyecto.datos(ModuloPuccetti.VIABILIDAD)`; no requiere repositorio propio.
"""
from .dominio import (
    COSTE_DEFAULT_OBRA_NUEVA_EUR_M2,
    COSTE_DEFAULT_REHABILITACION_EUR_M2,
    DefinicionEscenario,
    Escenario,
    Estado,
    EstudioViabilidad,
    EstudioViabilidadDCF,
    Financiacion,
    FlujoCaja,
    FuenteSuperficie,
    Intervencion,
    Operacion,
    ParametrosEconomicos,
    ResultadoEscenario,
    SupuestosDCF,
    TipologiaPR,
    UmbralesPR,
)
from .casos_uso import (
    CalcularViabilidad,
    CalcularViabilidadDCF,
    asociar_a_proyecto,
    asociar_dcf_a_proyecto,
    estudio_a_dict,
    estudio_dcf_a_dict,
    evaluar_umbrales,
    financiacion_a_dict,
    financiacion_desde_dict,
    financiacion_desde_proyecto,
    parametros_a_dict,
    parametros_desde_dict,
    parametros_desde_proyecto,
    semaforo_global,
    supuestos_dcf_a_dict,
    supuestos_dcf_desde_dict,
    supuestos_dcf_desde_proyecto,
    umbrales_a_dict,
    umbrales_desde_dict,
)

__all__ = [
    "COSTE_DEFAULT_OBRA_NUEVA_EUR_M2",
    "COSTE_DEFAULT_REHABILITACION_EUR_M2",
    "CalcularViabilidad",
    "CalcularViabilidadDCF",
    "DefinicionEscenario",
    "Escenario",
    "Estado",
    "EstudioViabilidad",
    "EstudioViabilidadDCF",
    "Financiacion",
    "FlujoCaja",
    "FuenteSuperficie",
    "Intervencion",
    "Operacion",
    "ParametrosEconomicos",
    "ResultadoEscenario",
    "SupuestosDCF",
    "TipologiaPR",
    "UmbralesPR",
    "asociar_a_proyecto",
    "asociar_dcf_a_proyecto",
    "estudio_a_dict",
    "estudio_dcf_a_dict",
    "evaluar_umbrales",
    "financiacion_a_dict",
    "financiacion_desde_dict",
    "financiacion_desde_proyecto",
    "parametros_a_dict",
    "parametros_desde_dict",
    "parametros_desde_proyecto",
    "semaforo_global",
    "supuestos_dcf_a_dict",
    "supuestos_dcf_desde_dict",
    "supuestos_dcf_desde_proyecto",
    "umbrales_a_dict",
    "umbrales_desde_dict",
]
